### ISSUE TITLE
error in updateWeather hangs homebridge

### ISSUE THREAD

**Issue by sejmann** [naofireblade/homebridge-weather-station-extended#12]
looks like wunderground returned incomplete data, and it hung homebridge, requiring a restart.  Maybe the whole thing should be wrapped in a try catch?

```
/opt/local/lib/node_modules/homebridge-weather-station-extended/index.js:323
						service.setCharacteristic(CustomCharacteristic.ForecastDay, forecast[day]['date']['weekday']);
						                                                                         ^

TypeError: Cannot read property 'date' of undefined
    at Wunderground.<anonymous> (/opt/local/lib/node_modules/homebridge-weather-station-extended/index.js:323:80)
    at Request._callback (/opt/local/lib/node_modules/homebridge-weather-station-extended/node_modules/wundergroundnode/lib/wundergroundnode.js:148:22)
    at Request.self.callback (/opt/local/lib/node_modules/homebridge-weather-station-extended/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/local/lib/node_modules/homebridge-weather-station-extended/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/local/lib/node_modules/homebridge-weather-station-extended/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
```

**Comment by naofireblade** [comment]
Good find. I will look into making this more robust but I don't have much time at the moment. If you feel comfortable enough with js you can submit a pull request if you want :) .

**Comment by naofireblade** [comment]
#13 reported the same problems later on
