### ISSUE TITLE
Change in Wunderground parameters?

### ISSUE THREAD

**Issue by BuckarooToo** [naofireblade/homebridge-weather-station-extended#13]
I'm getting a new error with this module. Is it possible that Wunderground changed how they arrange their parameters?:

/usr/lib/node_modules/homebridge-weather-station-extended/index.js:323
						service.setCharacteristic(CustomCharacteristic.ForecastDay, forecast[day]['date']['weekday']);
						                                                                         ^

TypeError: Cannot read property 'date' of undefined
    at Wunderground.<anonymous> (/usr/lib/node_modules/homebridge-weather-station-extended/index.js:323:80)
    at Request._callback (/usr/lib/node_modules/homebridge-weather-station-extended/node_modules/wundergroundnode/lib/wundergroundnode.js:148:22)
    at Request.self.callback (/usr/lib/node_modules/homebridge-weather-station-extended/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-weather-station-extended/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-weather-station-extended/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by naofireblade** [comment]
Looks like this happens more often recently. Thanks for reporting. I will try to fix this tomorrow.

**Comment by naofireblade** [comment]
Ist not working at all for you or just sometimes?

**Comment by naofireblade** [comment]
Can somebody give me his location? I guess wunderground fails to deliver forecasts in general for some regions at the moment because I have no problems with my location "Greifswald".

I will make the parsing more robust now.

**Comment by BuckarooToo** [comment]
The module does load initially, but then will fail within 24 hours. I'm still investigating if the date change is the culprit. Location is in the Boston, Massachusetts, USA area - zip code 02494 is the location I've used in the configuration script.

**Comment by naofireblade** [comment]
Thank you very much for helping on this problem. I checked your zip code and the response looks good so far. The strange thing is, the plugin runs fine in my location for months now so it will be hard to find the error.

I updated the index.js to catch exceptions while parsing and log the faulty API response. Can you please replace your index.js with the most recent one: https://github.com/naofireblade/homebridge-weather-station-extended/blob/master/index.js

Your index.js should be located here: /usr/lib/node_modules/homebridge-weather-station-extended/

**Comment by BuckarooToo** [comment]
Done. So far running just fine. I'll let you know if it stays up tomorrow.

**Comment by sejmann** [comment]
I'd wrapped the forecast update in a try catch a couple days ago, and it caught another error last night, but idiotically, I didn't output the response, so I'm not sure what triggered it.  I've now updated to using your updated index.js.  

Unrelatedly, I did notice 5 instances over the last few days of intermittant errors, appropriately caught, where the server seemed to complain that I wasn't supplying a key, but it seemed to benignly recover on the next call.

**Comment by usmcguy** [comment]
Mine still crashes after running a few hours

**Comment by sejmann** [comment]
@usmcguy with the new index.js?  Do you have any logs?

**Comment by usmcguy** [comment]
I'm good now, I updated yesterday apparently moments right before the update with the new index.js

**Comment by naofireblade** [comment]
The new index.js ist not published to npm yet because I want to find the error first. I don't want to fill the logs of all users.

You can fix your app (and help with testing) by replacing your index.js under `/usr/lib/node_modules/homebridge-weather-station-extended/`with this one: https://github.com/naofireblade/homebridge-weather-station-extended/blob/master/index.js

**Comment by naofireblade** [comment]
With your zip code I got the error as well. One at 20:57:31 CEST and one at 00:21:32 CEST.
Current conditions and forecast for today (day 0) are fine but forecast for day 1-3 is flawed. Since it occurs rarely I will just catch the parsing exception and wait for the next update interval.

**Comment by naofireblade** [comment]
Fixed in version [version 1.1.2](https://github.com/naofireblade/homebridge-weather-station-extended/releases/tag/v1.1.2)
You can update via `sudo npm update -g homebridge-weather-station-extended`

I will keep an eye on this in debug mode if it happens more frequently.

**Comment by naofireblade** [comment]
Thank you all very much for your help in reporting and fixing this issue 👍 .

**Comment by iRonin** [comment]
Just came across this error. Seems it occured only now (after one of the restarts of Homebridge).

**Comment by BuckarooToo** [comment]
Not sure if this helps - the module is running well (thanks!) and not exiting after errors. That said, here are examples of the errors generated to help you track this down:

[2018-1-16 09:13:07] [Weather Station] Exception while parsing forecast for day #0: TypeError: Cannot read property 'date' of undefined
[2018-1-16 09:13:07] [Weather Station] Exception while parsing forecast for day #1: TypeError: Cannot read property 'date' of undefined
[2018-1-16 09:13:07] [Weather Station] Exception while parsing forecast for day #2: TypeError: Cannot read property 'date' of undefined
[2018-1-16 09:13:07] [Weather Station] Exception while parsing forecast for day #3: TypeError: Cannot read property 'date' of undefined
[2018-1-17 00:17:51] [Weather Station] Error retrieving weather
[2018-1-17 00:17:51] [Weather Station] false
[2018-1-17 01:02:29] [Weather Station] Exception while parsing forecast for day #0: TypeError: Cannot read property 'date' of undefined
[2018-1-17 01:02:29] [Weather Station] Exception while parsing forecast for day #1: TypeError: Cannot read property 'date' of undefined
[2018-1-17 01:02:29] [Weather Station] Exception while parsing forecast for day #2: TypeError: Cannot read property 'date' of undefined
[2018-1-17 01:02:29] [Weather Station] Exception while parsing forecast for day #3: TypeError: Cannot read property 'date' of undefined

**Comment by naofireblade** [comment]
Thanks. I added a debug option in the release and tracked that down. I found out that sometimes the weather underground response has no forecast data (just an empty array).
```
simpleforecast: { forecastday: [] } }
```

**Comment by iRonin** [comment]
@naofireblade how to enable debug?

**Comment by naofireblade** [comment]
You have to change the homebridge start parameters:

Example: `sudo DEBUG=homebridge-weather-station-extended homebridge -D -U /var/lib/homebridge`

/var/lib/homebridge is my homebridge folder, it might be different depending on your installation. If you are running homebridge as a service, you can either change your start options or stop the service and start homebridge manually with the given example command.

This only works for plugins that use this package: https://www.npmjs.com/package/debug

**Comment by iRonin** [comment]
My log output:

```
[2018-1-19 12:25:23] [Weather Station] Exception while parsing forecast for day #2: TypeError: Cannot read property 'date' of undefined
Fri, 19 Jan 2018 11:25:23 GMT homebridge-weather-station-extended Response from Weather Underground API:
Fri, 19 Jan 2018 11:25:23 GMT homebridge-weather-station-extended { txt_forecast: { date: '11:59 PM CET', forecastday: [ [Object], [Object], [Object], [Object] ] }, simpleforecast: { forecastday: [ [Object], [Object] ] } }
Fri, 19 Jan 2018 11:25:23 GMT homebridge-weather-station-extended Update values for In 3 Days
[2018-1-19 12:25:23] [Weather Station] Exception while parsing forecast for day #3: TypeError: Cannot read property 'date' of undefined
Fri, 19 Jan 2018 11:25:23 GMT homebridge-weather-station-extended Response from Weather Underground API:
Fri, 19 Jan 2018 11:25:23 GMT homebridge-weather-station-extended { txt_forecast: { date: '11:59 PM CET', forecastday: [ [Object], [Object], [Object], [Object] ] }, simpleforecast: { forecastday: [ [Object], [Object] ] } }
```

**Comment by naofireblade** [comment]
Hi Ronin, thanks. Your simpleforecast {forecastday} array only has to objects (forecast for today and tomorrow). But the objects for in 2 days and in 3 days are missing.

Some minutes later all 4 objects are in the arrays. And some hours later maybe not.

This is clearly a weatherunderground bug. Nothing I can do about that.
