### ISSUE TITLE
Cannot read property 'date' of undefined

### ISSUE THREAD

**Issue by usmcguy** [naofireblade/homebridge-weather-station-extended#14]
A failure in the module is causing homebridge to crash.  Here is the output from my error file

`
TypeError: Cannot read property 'date' of undefined
    at Wunderground.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-station-extended/index.js:323:80)
    at Request._callback (/usr/local/lib/node_modules/homebridge-weather-station-extended/node_modules/wundergroundnode/lib/wundergroundnode.js:148:22)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-weather-station-extended/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-station-extended/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-station-extended/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`

**Comment by naofireblade** [comment]
Duplicated #13 .
