### ISSUE TITLE
1.2.2 crash

### ISSUE THREAD

**Issue by DeutscheMark** [naofireblade/homebridge-weather-station-extended#24]
homebridge crashes with the following log when updating the values in the Eve app.

```
/usr/lib/node_modules/homebridge-weather-station-extended/index.js:399
                                        pressure: this.accessories[i].currentConditionsService.getCharacteristic(Characteristic.AirPressure).value,
                                                                                                         ^
TypeError: Cannot read property 'value' of undefined
    at WeatherStationPlatform.addHistory (/usr/lib/node_modules/homebridge-weather-station-extended/index.js:399:106)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)
homebridge-weather.service: Main process exited, code=exited, status=1/FAILURE
homebridge-weather.service: Unit entered failed state.
homebridge-weather.service: Failed with result 'exit-code'.
```

**Comment by naofireblade** [comment]
Thanks for the report. Fixed in version 1.2.3.
